import streamlit as st

# Page configuration
st.set_page_config(page_title=" Research Findings", page_icon="🔬", layout="wide")

# 2. Global Theme Styling Injection (Updated Color Hierarchy)
st.markdown("""
    <style>
    @import url('https://googleapis.com');
    @import url('https://googleapis.com');

    /* Background and global body text styling (Slate Silver) */
    .main, p, div, label, span { 
        font-family: 'Inter', sans-serif !important; 
        font-size: 1.05rem;
        color: #94A3B8 !important; /* Premium silver text */
    }
    
    /* Main App Titles (Vibrant Electric Cyan) */
    h1 { 
        font-family: 'Lora', serif !important; 
        color: #00E5FF !important; 
        font-weight: 700;
    }
    
    /* Secondary Section Subheaders */
    h2, h3, h4 {
        font-family: 'Lora', serif !important; 
        color: #CBD5E1 !important; /* Soft white/gray for balance */
        font-weight: 600;
    }
    
    .main { background-color: #0E1117; }
    
    /* Interactive Control Buttons (Cyan to Dark Cyan Hover) */
    div.stButton > button:first-child {
        background-color: #00E5FF !important; 
        color: #0E1117 !important; 
        font-weight: bold;
        border-radius: 8px; 
        border: none; 
        padding: 0.5rem 2rem;
        font-family: 'Inter', sans-serif !important;
    }
    div.stButton > button:first-child:hover {
        background-color: #00B2CC !important; 
        color: #FFFFFF !important;
    }
    </style>
    """, unsafe_allow_html=True)


# Custom Sidebar Branding Logo (Matching Home)
st.sidebar.markdown("""
  st.sidebar.image("logo.png", use_container_width=True)
    st.sidebar.markdown("<br>", unsafe_allow_html=True)
except Exception:
    st.sidebar.warning("⚠️ logo.png asset not detected.")
    <div style='text-align: center; margin-bottom: 20px;'>
        <h1 style='font-size: 2.2rem; color: #00D2C4 !important; margin-bottom: 0px;'>🧬 PathoSonics</h1>
        <p style='font-size: 0.85rem; color: #888888; text-transform: uppercase; letter-spacing: 2px;'>Educational Sonification Lab</p>
    </div>
    <hr style='margin-top: 0px; margin-bottom: 20px; border-color: #1F2937;'>
""", unsafe_allow_html=True)

# Manuscript copy
st.title("🔬 Research Manuscript ")
st.caption("Parameter-Mapped Acoustic Profiling and Structural Disruption Auditing of Human Protein Variations")
st.markdown("---")

st.markdown("""
### Title: 
**Protein Auditing via Sound: Utilizing Parameter-Mapped Sonification of Amino Acid Hydrophobicity Indices to Identify Structural Missense Mutations**

#### 📄 Abstract
**Background:** Traditional genomic sequence auditing relies on visually tracking alphabetic text arrays, a method prone to human oversight and fatigue during long analytical sequences. Data sonification presents an alternative format, transforming complex biochemical data streams into distinct acoustic patterns. 

**Objective:** This study analyzes the specific musical findings generated by a custom-built amino-acid sonification tool to determine if single-point mutations produce reliable, recognizable acoustic signatures. 

**Methodology:** A specialized Python script translated the hydrophobicity values of amino acid chains into an interactive 4-octave C-Major Pentatonic scale. Multiple disease-relevant genetic pairs—including Hemoglobin (Sickle Cell) and p53 (Tumor Suppressor Variant)—were processed through the sound design engine to audit resulting pitch displacements and octave density changes. 

**Results:** The sonification findings revealed that single-point missense mutations generate stark, localized melodic shifts. Specifically, the hydrophilic-to-hydrophobic mutation in Sickle Cell hemoglobin triggered an immediate downward displacement of exactly 5 scale degrees (a shift from a bright 69 Hz note to a deep 38 Hz bass tone), while cancerous p53 variants demonstrated significant skewing toward low-octave cluster profiles. 

**Conclusion:** This research demonstrates that computational sonification transforms abstract biological structures into predictable, highly distinct musical intervals. This establishes sound profiling as a viable, non-visual tool for auditing genetic mutations and identifying structural data anomalies.

#### 1. Introduction
Modern bioinformatics generates immense datasets requiring advanced visualization modalities to preserve human interpretive accuracy. In clinical genomics, the identification of a single-point mutation requires meticulously scanning long strings of visual alphabetic text. This visual processing baseline can induce high cognitive strain and search fatigue over prolonged periods. 

To expand human cognitive data processing limits, research must pivot toward multimodal sensory displays. Because the human auditory system is optimized for real-time temporal pattern recognition and subtle frequency variance, data sonification offers an encouraging avenue. This study introduces an interactive data display platform designed to analyze whether structural mutations can be audited utilizing parameter-mapped sound design principles.
""")
